server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27016/lotto-web
  main:
    allow-bean-definition-overriding: true

lotto:
  number-generator:
    lotteryRunOccurrence: "0 0 12 * * 6"
    facade:
      numberOfNumbers: 25
      minimumNumber: 1
      maximumNumber: 99
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80
          connectionTimeout: 5000
          readTimeout: 5000
