server:
  port: 8082

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:63793}
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27016/lotto-web
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

lotto:
  result-checker:
    lotteryRunOccurrence: "0 55 11 * * 6"
  number-generator:
    lotteryRunOccurrence: "0 0 12 * * 6"

    facade:
      numberOfNumbers: 25
      minimumNumber: 1
      maximumNumber: 99
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80
          connectionTimeout: 5000
          readTimeout: 5000
auth:
  jwt:
    secretKey: ${JWT_SECRET}
    expirationDays: 30
    issuer: job-offers-backend